apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: release-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - mirror.hub.mylab.com:8443/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - mirror.hub.mylab.com:8443/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
