kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 4                                                      
storageConfig:                                                      
  registry:
    imageURL: ip-172-17-1-133.ap-southeast-1.compute.internal:8443/mirror/oc-mirror-metadata                 
    skipTLS: false
mirror:
  platform:
    channels:
    - name: stable-4.16
      minVersion: 4.16.25                                    
      maxVersion: 4.16.25                                    
      type: ocp
    graph: true                                                     
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
    packages:
    - name: aws-efs-csi-driver-operator                                     
      channels:
      - name: stable                                                
    - name: sandboxed-containers-operator         
      channels:
      - name: stable                                        
    - name: trustee-operator
      channels:
      - name: stable                                                
    - name: nfd                                
      channels:
      - name: stable                                                
  additionalImages:
  - name: registry.redhat.io/ubi9/ubi:latest                        
  helm: {}

